/*
This is the function implementation file for the player class
*/

#include "Player.hpp"


/* Constructor for the Player class */
Player::Player()
{
	this->hits = 5;
	this->atk = 2;
}

/* Attack function will generate and return a random value between atk and atk * 3 */
int Player::attack(Enemy *enemy)
{
	int attack = (rand() % (atk * 3 - atk + 1)) + atk;
	cout << "You attack the " << enemy->getName() << " for " << attack << " damage!" << endl;
	return attack;
}

/* Defense function will take the damage generated by an enemy and subtract that value from hits */
void Player::defense(int damage)
{
	this->hits = this->hits - damage;
	checkSlain();
}

/* Function will print a message if the player's hits drop <= 0*/
void Player::checkSlain()
{
	if (this->hits <= 0) {
		cout << "\nYou have been slain!" << endl;
	}
}

/* This function will return the hits of the Player object. */
int Player::getHits()
{
	return this->hits;
}

/* Destructor for the Player class */
Player::~Player()
{
}
